#!/usr/bin/env python3
"""
Generate multi-turn datapoints where each user turn is generated by a
separate LLM based on the dialog blueprint and prior conversation context.

Usage:
    python generate_multi_turn.py [OPTIONS]

Options:
    --num-datapoints N      Number of datapoints to generate (default: 10)
    --num-turns N           Number of user-assistant turns (default: 2)
    --actions-per-turn N    Tool calls per turn (default: 2)
    --output FILE           Output file path (default: multi_turn_datapoints.jsonl)
    --model MODEL           Model name (default: z-ai/glm-5.1)
"""

import json
import os
import sys
import random
import argparse
from datetime import datetime
from dotenv import load_dotenv
from pathlib import Path

sys.stdout.reconfigure(line_buffering=True)
sys.stderr.reconfigure(line_buffering=True)

load_dotenv()

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from llm_client import LocalOpenAILLMClient
from tool_manager import ToolManager
from apigen_multi_turn import MultiTurnGenerator, MultiTurnDatapoint


def parse_args():
    parser = argparse.ArgumentParser(
        description='Generate multi-turn datapoints with step-by-step tool simulation.'
    )
    parser.add_argument('--num-datapoints', '-n', type=int, default=10,
                        help='Number of datapoints to generate (default: 10)')
    parser.add_argument('--num-turns', '-t', type=int, default=2,
                        help='Number of user-assistant turns (default: 2)')
    parser.add_argument('--actions-per-turn', '-a', type=int, default=2,
                        help='Tool calls per turn (default: 2)')
    parser.add_argument('--output', '-o', type=str, default='multi_turn_datapoints.jsonl',
                        help='Output file path')
    parser.add_argument('--tool-pool', type=str,
                        default='~/data/APIGen-MT/magnet_tool_extraction/bfcl_v3_tools_with_outputs.jsonl',
                        help='Path to tool pool file')
    parser.add_argument('--invocation-examples', type=str,
                        default='~/data/APIGen-MT/magnet_tool_extraction/bfcl_v3_invocation_examples.jsonl',
                        help='Path to invocation examples file')
    parser.add_argument('--model', '-m', type=str, default='minimax-m2.7',
                        help='Model to use for generation (default: minimax-m2.7)')
    parser.add_argument('--category', '-c', type=str, default=None,
                        help='Focus category (e.g., Communication, Events, Finance, Posting Api, Science, Storage, Travel Booking, Vehicle Control). If not specified, randomly selected.')
    return parser.parse_args()


def load_tool_categories(tool_pool_path: str) -> dict:
    tools_by_category = {}
    with open(tool_pool_path, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                tool = json.loads(line.strip())
                category = tool.get('category', 'Unknown')
                tools_by_category.setdefault(category, []).append(tool)
            except json.JSONDecodeError:
                continue
    return tools_by_category


def main():
    args = parse_args()

    tool_pool_path = str(Path(args.tool_pool).expanduser())
    invocation_examples_path = str(Path(args.invocation_examples).expanduser())

    print("=" * 70)
    print("MULTI-TURN DATAPOINT GENERATION")
    print("=" * 70)
    print(f"Target: {args.num_datapoints} datapoints")
    print(f"Turns per conversation: {args.num_turns}")
    print(f"Actions per turn: {args.actions_per_turn}")
    print(f"Output: {args.output}")
    print(f"Model: {args.model}")
    print("=" * 70)

    api_key = os.getenv("OPENAI_API_KEY")
    api_base = os.getenv("OPENAI_API_BASE")
    if not api_key or not api_base:
        print("ERROR: OPENAI_API_KEY or OPENAI_API_BASE not set")
        sys.exit(1)

    llm_client = LocalOpenAILLMClient(
        url=api_base,
        api_key=api_key,
        api_model=args.model,
        hf_tokenizer_id=None,
    )

    print("\nLoading tools...")
    tools_by_category = load_tool_categories(tool_pool_path)
    total_tools = sum(len(t) for t in tools_by_category.values())
    print(f"Loaded {total_tools} tools across {len(tools_by_category)} categories")
    for cat, tools in sorted(tools_by_category.items()):
        print(f"  {cat:30s}: {len(tools):3d} tools")

    tool_manager = ToolManager(
        llm=llm_client,
        tool_pool_path=tool_pool_path,
        invocation_examples_path=invocation_examples_path,
    )

    generator = MultiTurnGenerator(
        llm_client=llm_client,
        tool_manager=tool_manager,
        num_turns=args.num_turns,
        actions_per_turn=args.actions_per_turn,
    )

    output_dir = Path(args.output).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    datapoints = []
    categories = sorted(tools_by_category.keys())

    while len(datapoints) < args.num_datapoints:
        remaining = args.num_datapoints - len(datapoints)

        print(f"\n{'=' * 70}")
        print(f"Generated: {len(datapoints)}/{args.num_datapoints} | Remaining: {remaining}")
        print("=" * 70)

        if args.category:
            focus_category = args.category
            if focus_category not in categories:
                print(f"ERROR: Unknown category '{focus_category}'. Available: {categories}")
                sys.exit(1)
        else:
            focus_category = random.choice(categories)

        print(f"\nFocus category: {focus_category}")

        dp = generator.generate_multi_turn_datapoint(focus_category=focus_category)

        if dp is None:
            print("  ✗ Generation failed, retrying...")
            continue

        dp_dict = dp.model_dump()
        dp_dict['timestamp'] = datetime.now().isoformat()

        with open(args.output, 'a', encoding='utf-8') as f:
            f.write(json.dumps(dp_dict, ensure_ascii=False) + '\n')

        datapoints.append(dp)
        print(f"\n✓ Datapoint {len(datapoints)} generated")
        print(f"  Task: {dp.conversation.overall_task}")
        print(f"  Turns: {len(dp.conversation.turns)}")
        print(f"  Tools used: {dp.conversation.tools_used}")

    print("\n" + "=" * 70)
    print("GENERATION COMPLETE")
    print("=" * 70)
    print(f"Total generated: {len(datapoints)}/{args.num_datapoints}")
    print(f"Output file: {args.output}")

    tool_counter = {}
    for dp in datapoints:
        for t in dp.conversation.tools_used:
            tool_counter[t] = tool_counter.get(t, 0) + 1

    print(f"\nTop tools used:")
    for t, c in sorted(tool_counter.items(), key=lambda x: -x[1])[:15]:
        print(f"  {t}: {c}")

    total_calls = sum(dp.token_usage.total_llm_calls for dp in datapoints)
    total_tokens = sum(dp.token_usage.total_tokens for dp in datapoints)
    print(f"\nToken Usage Statistics:")
    print(f"  Total LLM calls: {total_calls}")
    print(f"  Total tokens: {total_tokens:,}")
    if datapoints:
        print(f"  Average per datapoint:")
        print(f"    - LLM calls: {total_calls / len(datapoints):.1f}")
        print(f"    - Tokens: {total_tokens // len(datapoints):,}")


if __name__ == "__main__":
    main()